CREATE TABLE "CUSTOMER" (CUST_ID INTEGER PRIMARY KEY AUTOINCREMENT, MOBILE_NUMBER 
INTEGER NOT NULL, ADDRESS TEXT NOT NULL, CUSTOMER_NAME TEXT NOT NULL, GUARDIAN_NAME TEXT
 NOT NULL, PHOTO_CUSTOMER TEXT NOT NULL, 
CREATED_DATE TIMESTAMP NOT NULL);

CREATE UNIQUE INDEX pk_cust_index ON "CUSTOMER"("MOBILE_NUMBER");

CREATE TABLE TRANSACTIONS (       
TRAN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
CUST_ID INTEGER NOT NULL,
TAKEN_DATE TIMESTAMP NOT NULL ,
TAKEN_AMOUNT  INTEGER    NOT NULL ,
RATE_OF_INTEGEREREST  DOUBLE    NOT NULL ,
ITEM_NAME  TEXT    NOT NULL ,
TRANSACTION_TYPE  INTEGER     NOT NULL ,
PAID_DATE  TIMESTAMP    NOT NULL ,
VIA  TEXT    NOT NULL ,
PAID_AMOUNT  INTEGER    NOT NULL ,
TOTAL_INTEGERREST  FLOAT    NOT NULL ,
DUE_TIME  TEXT    NOT NULL ,
PHOTO_PROOF  TEXT    NOT NULL ,
PHOTO_ITEM  TEXT    NOT NULL ,
CREATED_DATE  TIMESTAMP    NOT NULL, 
 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) 
);

CREATE UNIQUE INDEX pk_trans_index ON "TRANSACTIONS"("TRAN_ID","CUST_ID");

PRAGMA foreign_keys = ON;