// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFJ1jCrkDMRbvNH5lyvCIia8pSkc9s_s',
    appId: '1:670447424946:web:d37a0901fd2322a19600ab',
    messagingSenderId: '670447424946',
    projectId: 'self-finance-2230a',
    authDomain: 'self-finance-2230a.firebaseapp.com',
    storageBucket: 'self-finance-2230a.appspot.com',
    measurementId: 'G-MX9Q6DH4H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDATu1jSh88sS3PEje1yRoEeYpI6tXiNhQ',
    appId: '1:670447424946:android:27dc3ab8b3ba9d639600ab',
    messagingSenderId: '670447424946',
    projectId: 'self-finance-2230a',
    storageBucket: 'self-finance-2230a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9I4GzrU3txdza61ru6Vkwe2vyRW5aDw',
    appId: '1:670447424946:ios:8e61b61d6c219bfc9600ab',
    messagingSenderId: '670447424946',
    projectId: 'self-finance-2230a',
    storageBucket: 'self-finance-2230a.appspot.com',
    iosBundleId: 'com.vamshikrishna.selfFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9I4GzrU3txdza61ru6Vkwe2vyRW5aDw',
    appId: '1:670447424946:ios:8e61b61d6c219bfc9600ab',
    messagingSenderId: '670447424946',
    projectId: 'self-finance-2230a',
    storageBucket: 'self-finance-2230a.appspot.com',
    iosBundleId: 'com.vamshikrishna.selfFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQFJ1jCrkDMRbvNH5lyvCIia8pSkc9s_s',
    appId: '1:670447424946:web:70de0171e72066659600ab',
    messagingSenderId: '670447424946',
    projectId: 'self-finance-2230a',
    authDomain: 'self-finance-2230a.firebaseapp.com',
    storageBucket: 'self-finance-2230a.appspot.com',
    measurementId: 'G-MLREEGSM9N',
  );

}